version: '3'

services: 
    db:
        image: mongo
        volumes: 
            - ./db:/docker-entrypoint-initdb.d/
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=shop
        ports: 
            - 27017:27017

    # back:
    #     build: ./shopping/
    #     ports: 
    #         - 3000:3000

    # front:
    #     build: ./shopping-front/
    #     ports: 
    #         - 80:80